name: "Integration tests against current main branch"

on: [push]

jobs:
  test:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4

      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: run unit tests
        run: make test-unit

      - name: build the binary
        run: make exe && tar -cf coyote.tar build/bin/coyote

      - name: upload the binary as an artefact
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        id: upload_coyote
        with:
          path: coyote.tar
          name: coyote.tar

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Configure git so it doesn't error out
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: run functional tests
        run: |
          make deps
          test/functional/.venv/bin/python -m pytest test/functional/test_apply.py -k test_apply_records_package_as_installed

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: grab the coyote binary
        uses: actions/download-artifact@v4
        id: download_coyote
        with:
          name: coyote.tar

      - run: tar -xf "${{steps.download_coyote.outputs.download-path}}/coyote.tar"

      - name: build the release packages
        run: make -j4 packages

      - name: perform the release
        run: build/bin/coyote release ${{github.ref}} build/*.tgz
